services:
  kanban-dev:
    build:
      context: .
    container_name: kanban-dev
    network_mode: host
    volumes:
      - /home/ubuntu:/home/max
    restart: always
    environment:
      - NODE_ENV=production
    command: ['npx', '--yes', 'kanban@latest', '--host', '0.0.0.0', '--port', '3484']
